# Generated by Django 5.2.17 on 2026-08-07 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('glove', 'Glove'), ('kart_unit', 'Kart Unit'), ('biometric_strap', 'Biometric Strap')], help_text='Type of IoT device', max_length=20)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('pairing', 'Pairing'), ('offline', 'Offline')], default='offline', help_text='Current connection status of the device', max_length=15)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last time the device sent data to the server', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User this device is currently assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['device_type'],
            },
        ),
    ]
