# Generated by Django 5.2.17 on 2026-08-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='api_key_hash',
            field=models.CharField(blank=True, default='', help_text="SHA-256 hash of the device's secret API key token", max_length=128),
        ),
    ]
