# Generated by Django 5.2.17 on 2026-09-18 06:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_api_key_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(choices=[('self_test', 'Self Test')], help_text='Type of command to execute', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Execution status of the command', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='When the command was queued')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the command was completed or failed', null=True)),
                ('result', models.JSONField(blank=True, help_text='Structured result payload from the device', null=True)),
                ('device', models.ForeignKey(help_text='The device this command is for', on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.device')),
                ('requested_by', models.ForeignKey(blank=True, help_text='The Admin user who triggered this command', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_device_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_commands',
                'ordering': ['-requested_at'],
            },
        ),
    ]
