# Generated by Django 5.2.17 on 2026-08-07 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('safety', 'Safety'), ('performance', 'Performance')], default='safety', help_text='Session mode — determines alert thresholds and coaching focus', max_length=15)),
                ('goal_text', models.TextField(blank=True, default='', help_text="Free-text coaching goal for this session (e.g. 'Zero red alerts at the Hairpin')")),
                ('goal_passed', models.BooleanField(blank=True, help_text='Whether the driver met the session goal — null if not yet evaluated', null=True)),
                ('started_at', models.DateTimeField(help_text='When the session began (first telemetry timestamp)')),
                ('ended_at', models.DateTimeField(blank=True, help_text='When the session ended — null if still active', null=True)),
                ('driver', models.ForeignKey(help_text='The driver for this session', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(help_text='The track where this session took place', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tracks.track')),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BiometricReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(help_text='Timestamp of this biometric reading')),
                ('heart_rate', models.IntegerField(help_text='Heart rate in BPM')),
                ('spo2', models.IntegerField(help_text='Blood oxygen saturation percentage (SpO2)')),
                ('breathing_rate', models.IntegerField(blank=True, help_text='Breathing rate in breaths per minute', null=True)),
                ('session', models.ForeignKey(help_text='The session this biometric reading belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='biometric_readings', to='driving_sessions.session')),
            ],
            options={
                'db_table': 'biometric_readings',
                'ordering': ['session', 'recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('amber', 'Amber'), ('red', 'Red')], help_text='Alert severity — amber (approaching) or red (exceeded)', max_length=5)),
                ('g_value', models.FloatField(help_text='The actual g-force value that triggered the alert')),
                ('threshold_applied', models.FloatField(help_text='The threshold that was in effect when the alert fired — may be a driver-specific custom threshold or the zone default')),
                ('triggered_at', models.DateTimeField(help_text='When the alert was triggered')),
                ('zone', models.ForeignKey(help_text='The zone where the threshold was exceeded', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tracks.zone')),
                ('session', models.ForeignKey(help_text='The session during which this alert fired', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='driving_sessions.session')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_text', models.TextField(help_text='The coaching note content')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this note was created')),
                ('coach', models.ForeignKey(help_text='The coach who wrote this note', on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='The session this note is about', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='driving_sessions.session')),
                ('zone', models.ForeignKey(blank=True, help_text='Specific zone this note refers to (null for general session notes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_notes', to='tracks.zone')),
            ],
            options={
                'db_table': 'session_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(help_text='Timestamp of this sensor reading')),
                ('lateral_g', models.FloatField(help_text='Lateral g-force measured by the IMU')),
                ('speed_kmh', models.FloatField(help_text='Speed in km/h from the GPS module')),
                ('gps_lat', models.FloatField(help_text='GPS latitude')),
                ('gps_lng', models.FloatField(help_text='GPS longitude')),
                ('session', models.ForeignKey(help_text='The session this reading belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_readings', to='driving_sessions.session')),
                ('zone', models.ForeignKey(blank=True, help_text='The zone where this reading was taken (null if on a straight)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telemetry_readings', to='tracks.zone')),
            ],
            options={
                'db_table': 'telemetry',
                'ordering': ['session', 'recorded_at'],
                'indexes': [models.Index(fields=['session', 'recorded_at'], name='idx_telemetry_session_time')],
            },
        ),
    ]
