# Generated by Django 5.2.17 on 2026-08-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='kart_number',
            field=models.CharField(blank=True, help_text="Kart identifier (e.g. '#12')", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='lap_number',
            field=models.PositiveIntegerField(blank=True, help_text='Lap number within the session', null=True),
        ),
    ]
