# Generated by Django 5.2.17 on 2026-08-07 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name for the track (e.g. 'Kari Motor Speedway')", max_length=150)),
                ('reference_line', models.JSONField(blank=True, help_text='GPS coordinates of the ideal racing line (JSON array of lat/lng points)', null=True)),
                ('kart_class', models.CharField(choices=[('rental', 'Rental'), ('sprint', 'Sprint')], default='rental', help_text='Type of karts used on this track — affects threshold calibration', max_length=10)),
                ('surveyed_at', models.DateTimeField(blank=True, help_text='When the track was last surveyed for zone boundaries', null=True)),
                ('created_by', models.ForeignKey(help_text='User who added this track to the system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tracks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="Human-readable name (e.g. 'Hairpin', 'Sweeper', 'Chicane')", max_length=100)),
                ('threshold_g', models.FloatField(help_text='Calibrated safe g-force limit for this zone — driver thresholds cannot exceed this')),
                ('gps_range', models.JSONField(blank=True, help_text='GPS boundary for this zone (JSON with start/end coordinates)', null=True)),
                ('track', models.ForeignKey(help_text='The track this zone belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='tracks.track')),
            ],
            options={
                'db_table': 'zones',
                'ordering': ['track', 'label'],
            },
        ),
    ]
