# Generated by Django 5.2.17 on 2026-08-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='corner_type',
            field=models.CharField(blank=True, choices=[('hairpin', 'Hairpin'), ('sweeper', 'Sweeper'), ('chicane', 'Chicane'), ('straight', 'Straight'), ('other', 'Other')], default='other', help_text='Fixed category classification for corner type', max_length=20),
        ),
        migrations.AlterField(
            model_name='zone',
            name='threshold_g',
            field=models.FloatField(default=1.15, help_text='Calibrated safe g-force limit for this zone — driver thresholds cannot exceed this'),
        ),
    ]
