# Generated by Django 5.2.17 on 2026-08-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_zone_corner_type_alter_zone_threshold_g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='threshold_g',
            field=models.FloatField(default=1.5, help_text='Calibrated safe g-force limit for this zone — driver thresholds cannot exceed this'),
        ),
    ]
