# Generated by Django 5.2.17 on 2026-08-07 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this user', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address — used as the login identifier', max_length=254, unique=True)),
                ('name', models.CharField(help_text='Display name shown in the UI', max_length=150)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('coach', 'Coach'), ('driver', 'Driver')], help_text='Determines which dashboard and API endpoints the user can access', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivated users cannot log in. Admin can deactivate accounts.')),
                ('is_staff', models.BooleanField(default=False, help_text="Django admin site access flag — not used in Trackside's own auth")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this account was created')),
                ('created_by', models.ForeignKey(blank=True, help_text='The admin who created this account (null for the seeded admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['name'],
            },
        ),
    ]
