# Generated by Django 5.2.17 on 2026-08-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, editable=False, help_text='System-generated unique login identifier (e.g. TRK-DRV-000042)', max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address — optional for Drivers, required for Coach/Admin', max_length=254, null=True, unique=True),
        ),
    ]
