# Generated by Django 5.2.17 on 2026-08-14 03:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE_USER', 'Create User'), ('UPDATE_USER', 'Update User'), ('DEACTIVATE_USER', 'Deactivate User'), ('REACTIVATE_USER', 'Reactivate User'), ('DELETE_USER', 'Delete User')], help_text='Type of action performed', max_length=30)),
                ('target_user_id', models.CharField(blank=True, help_text='ID of the modified user', max_length=64, null=True)),
                ('target_user_name', models.CharField(blank=True, help_text='Display name of the target user', max_length=150, null=True)),
                ('details', models.TextField(blank=True, default='', help_text='Human-readable description of changes made')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the modification occurred')),
                ('actor', models.ForeignKey(blank=True, help_text='The admin user who initiated this modification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log_entries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
