# Generated by Django 5.2.17 on 2026-08-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='tutorial_completed',
            field=models.BooleanField(default=False, help_text='Whether the user has completed or dismissed the per-role dashboard tutorial'),
        ),
    ]
