# Generated by Django 5.2.17 on 2026-08-18 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_userpreference_tutorial_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='theme',
        ),
    ]
