# Generated by Django 5.2.17 on 2026-08-07 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverZoneThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_threshold_g', models.FloatField(help_text='Custom g-force threshold — must be ≤ zone.threshold_g')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='When this threshold was set — latest row is the active threshold')),
                ('driver', models.ForeignKey(help_text='The driver this custom threshold applies to', on_delete=django.db.models.deletion.CASCADE, related_name='zone_thresholds', to=settings.AUTH_USER_MODEL)),
                ('set_by', models.ForeignKey(help_text='The coach who set this threshold', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thresholds_set', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(help_text='The zone this custom threshold applies to', on_delete=django.db.models.deletion.CASCADE, related_name='driver_thresholds', to='tracks.zone')),
            ],
            options={
                'db_table': 'driver_zone_thresholds',
                'ordering': ['-updated_at'],
            },
        ),
    ]
